/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated/productos'
import { Route as AuthenticatedPianiRouteImport } from './routes/_authenticated/piani'
import { Route as AuthenticatedSociIndexRouteImport } from './routes/_authenticated/soci.index'
import { Route as AuthenticatedSociNuovoRouteImport } from './routes/_authenticated/soci.nuovo'
import { Route as AuthenticatedSociGestisciRouteImport } from './routes/_authenticated/soci.gestisci'
import { Route as AuthenticatedSociIdRouteImport } from './routes/_authenticated/soci.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPianiRoute = AuthenticatedPianiRouteImport.update({
  id: '/piani',
  path: '/piani',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSociIndexRoute = AuthenticatedSociIndexRouteImport.update({
  id: '/soci/',
  path: '/soci/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSociNuovoRoute = AuthenticatedSociNuovoRouteImport.update({
  id: '/soci/nuovo',
  path: '/soci/nuovo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSociGestisciRoute =
  AuthenticatedSociGestisciRouteImport.update({
    id: '/soci/gestisci',
    path: '/soci/gestisci',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSociIdRoute = AuthenticatedSociIdRouteImport.update({
  id: '/soci/$id',
  path: '/soci/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/piani': typeof AuthenticatedPianiRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/soci/$id': typeof AuthenticatedSociIdRoute
  '/soci/gestisci': typeof AuthenticatedSociGestisciRoute
  '/soci/nuovo': typeof AuthenticatedSociNuovoRoute
  '/soci/': typeof AuthenticatedSociIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/piani': typeof AuthenticatedPianiRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/': typeof AuthenticatedIndexRoute
  '/soci/$id': typeof AuthenticatedSociIdRoute
  '/soci/gestisci': typeof AuthenticatedSociGestisciRoute
  '/soci/nuovo': typeof AuthenticatedSociNuovoRoute
  '/soci': typeof AuthenticatedSociIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/piani': typeof AuthenticatedPianiRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/soci/$id': typeof AuthenticatedSociIdRoute
  '/_authenticated/soci/gestisci': typeof AuthenticatedSociGestisciRoute
  '/_authenticated/soci/nuovo': typeof AuthenticatedSociNuovoRoute
  '/_authenticated/soci/': typeof AuthenticatedSociIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/piani'
    | '/productos'
    | '/soci/$id'
    | '/soci/gestisci'
    | '/soci/nuovo'
    | '/soci/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/piani'
    | '/productos'
    | '/'
    | '/soci/$id'
    | '/soci/gestisci'
    | '/soci/nuovo'
    | '/soci'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/piani'
    | '/_authenticated/productos'
    | '/_authenticated/'
    | '/_authenticated/soci/$id'
    | '/_authenticated/soci/gestisci'
    | '/_authenticated/soci/nuovo'
    | '/_authenticated/soci/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/piani': {
      id: '/_authenticated/piani'
      path: '/piani'
      fullPath: '/piani'
      preLoaderRoute: typeof AuthenticatedPianiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soci/': {
      id: '/_authenticated/soci/'
      path: '/soci'
      fullPath: '/soci/'
      preLoaderRoute: typeof AuthenticatedSociIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soci/nuovo': {
      id: '/_authenticated/soci/nuovo'
      path: '/soci/nuovo'
      fullPath: '/soci/nuovo'
      preLoaderRoute: typeof AuthenticatedSociNuovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soci/gestisci': {
      id: '/_authenticated/soci/gestisci'
      path: '/soci/gestisci'
      fullPath: '/soci/gestisci'
      preLoaderRoute: typeof AuthenticatedSociGestisciRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soci/$id': {
      id: '/_authenticated/soci/$id'
      path: '/soci/$id'
      fullPath: '/soci/$id'
      preLoaderRoute: typeof AuthenticatedSociIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPianiRoute: typeof AuthenticatedPianiRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSociIdRoute: typeof AuthenticatedSociIdRoute
  AuthenticatedSociGestisciRoute: typeof AuthenticatedSociGestisciRoute
  AuthenticatedSociNuovoRoute: typeof AuthenticatedSociNuovoRoute
  AuthenticatedSociIndexRoute: typeof AuthenticatedSociIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPianiRoute: AuthenticatedPianiRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSociIdRoute: AuthenticatedSociIdRoute,
  AuthenticatedSociGestisciRoute: AuthenticatedSociGestisciRoute,
  AuthenticatedSociNuovoRoute: AuthenticatedSociNuovoRoute,
  AuthenticatedSociIndexRoute: AuthenticatedSociIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
